name: Create Github Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Test code
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
      - name: Build code
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Watch the CHANGELOG.MD file
          draft: false
          prerelease: false
