name: Create Npm Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install dependencies with node
        uses: actions/setup-node@v1
        with:
          node-version: 13.7
          always-auth: true
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - run: yarn login --registry=https://npm.pkg.github.com --scope=@thecreazy
      - run: yarn publish --access public